from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

from .projections import _normalize_name, _prepared_stats, _project_player, calculate_fantasy_points


ACTUAL_STAT_FIELDS = (
    "passing_yards",
    "passing_tds",
    "interceptions",
    "rushing_yards",
    "rushing_tds",
    "receptions",
    "receiving_yards",
    "receiving_tds",
)


def build_projection_accuracy_table(
    raw_stats: pd.DataFrame,
    leagues_df: pd.DataFrame,
    config: dict[str, Any],
    history_path: Path,
) -> pd.DataFrame:
    """Grades each projection source's historical accuracy, feeding consensus
    weighting in projections.py. nflverse_history is graded retrospectively against
    its own held-out prior-season actuals -- no snapshot needed, both are already in
    one player_stats.csv load. fantasy_nerds needs a real week-over-week snapshot
    (see append_projection_accuracy_snapshot) since it is a live source with no
    history yet; this advances docs/sprint_plan.md Sprint 10's already-documented
    append-only snapshot pattern in minimal form."""
    scoring = _scoring_settings_from_leagues(leagues_df)
    lookback_weeks = int(((config.get("projection_sources") or {}).get("accuracy_grading") or {}).get("lookback_weeks", 4))
    rows = _grade_nflverse_history(raw_stats, str(config.get("current_season", "")), scoring)
    # lookback_weeks scales the safety cap on how much snapshot history to grade in one
    # pass -- not a precise week-boundary filter (see docstring caveat below), just a
    # config-responsive bound.
    rows.extend(_grade_fantasy_nerds_from_snapshots(history_path, raw_stats, scoring, lookback_snapshots=lookback_weeks * 500))
    return pd.DataFrame(rows, columns=_accuracy_columns())


def append_projection_accuracy_snapshot(
    history_path: Path,
    projection_source_components_df: pd.DataFrame,
    config: dict[str, Any],
) -> None:
    """Append-only projection history log for live (non-backtestable) sources.
    Advances docs/sprint_plan.md Sprint 10's documented projection_snapshots pattern
    -- deliberately NOT part of the overwrite-every-refresh export loop. Dated-key
    idempotent: a rerun for the same (season, week, source, player_id) replaces its
    own prior row instead of duplicating, matching Sprint 10's acceptance criteria
    ("Historical rows are append-only unless explicitly regenerated by dated key")."""
    if projection_source_components_df is None or projection_source_components_df.empty:
        return
    fn_rows = projection_source_components_df[projection_source_components_df.get("source") == "fantasy_nerds"]
    if fn_rows.empty:
        return

    current_week = config.get("current_week") or 1
    now = datetime.now(timezone.utc).isoformat()
    snapshot_rows = [
        {
            "season": row.get("season", ""),
            "week": current_week,
            "source": "fantasy_nerds",
            "player_id": row.get("player_id", ""),
            "player_name": row.get("player_name", ""),
            "position": row.get("position", ""),
            "projected_fantasy_points": row.get("projected_fantasy_points", 0.0),
            "written_at": now,
        }
        for _, row in fn_rows.iterrows()
    ]
    snapshot_df = pd.DataFrame(snapshot_rows, columns=_snapshot_history_columns())

    history_path.parent.mkdir(parents=True, exist_ok=True)
    if history_path.exists():
        try:
            existing = pd.read_csv(history_path)
        except Exception:
            existing = pd.DataFrame(columns=_snapshot_history_columns())
        combined = pd.concat([existing, snapshot_df], ignore_index=True)
        combined = combined.drop_duplicates(subset=["season", "week", "source", "player_id"], keep="last")
        combined.to_csv(history_path, index=False)
    else:
        snapshot_df.to_csv(history_path, index=False)


def _grade_nflverse_history(raw_stats: pd.DataFrame, current_season: str, scoring: dict[str, float]) -> list[dict[str, Any]]:
    if not current_season.isdigit() or raw_stats is None or raw_stats.empty:
        return []
    prior_season = int(current_season) - 1

    frame = raw_stats.copy()
    frame["season"] = pd.to_numeric(frame.get("season"), errors="coerce")
    if "season_type" in frame:
        frame = frame[frame["season_type"] == "REG"]
    frame["normalized_name"] = frame.apply(
        lambda row: _normalize_name(row.get("player_display_name") or row.get("player_name")), axis=1
    )

    actual_rows = frame[frame["season"] == prior_season]
    if actual_rows.empty:
        return []

    # Mirrors _prepared_stats' own 2-season lookback, just anchored one season
    # earlier -- reproduces exactly what the method would have projected entering
    # prior_season using only data that would have existed at that time.
    backtest_stats = _prepared_stats(raw_stats, str(prior_season))
    backtest_groups = (
        {name: group for name, group in backtest_stats.groupby("normalized_name")} if not backtest_stats.empty else {}
    )

    errors_by_position: dict[str, list[float]] = {}
    for normalized_name, player_weeks in actual_rows.groupby("normalized_name"):
        if not normalized_name:
            continue
        position = str(player_weeks.iloc[0].get("position", ""))
        projected = _project_player(backtest_groups.get(normalized_name, pd.DataFrame()), scoring, position)
        if projected["projection_method"] == "missing_nflverse_history":
            continue
        projected_ppg = projected["projected_ppg"]
        for _, week_row in player_weeks.iterrows():
            actual_points = calculate_fantasy_points(_actual_stat_payload(week_row), scoring, position)
            errors_by_position.setdefault(position, []).append(abs(actual_points - projected_ppg))

    return _rows_from_errors_by_position("nflverse_history", prior_season, errors_by_position, "nflverse player_stats.csv retrospective weekly backtest")


def _grade_fantasy_nerds_from_snapshots(
    history_path: Path, raw_stats: pd.DataFrame, scoring: dict[str, float], lookback_snapshots: int = 2000
) -> list[dict[str, Any]]:
    if not history_path.exists() or raw_stats is None or raw_stats.empty:
        return []
    try:
        history = pd.read_csv(history_path)
    except Exception:
        return []
    if history.empty or "source" not in history.columns:
        return []
    fn_history = history[history["source"] == "fantasy_nerds"]
    if fn_history.empty:
        return []
    # Generous soft cap on how much history to grade in one pass, same posture as
    # accuracy.py's precedent elsewhere in this codebase's history -- not a precise
    # trailing-N-weeks window, just a safety bound.
    fn_history = fn_history.sort_values("written_at").tail(lookback_snapshots)

    frame = raw_stats.copy()
    frame["season"] = pd.to_numeric(frame.get("season"), errors="coerce")
    frame["week"] = pd.to_numeric(frame.get("week"), errors="coerce")
    if "season_type" in frame:
        frame = frame[frame["season_type"] == "REG"]
    frame["normalized_name"] = frame.apply(
        lambda row: _normalize_name(row.get("player_display_name") or row.get("player_name")), axis=1
    )

    errors_by_position: dict[str, list[float]] = {}
    graded_season = ""
    for _, snapshot in fn_history.iterrows():
        season = pd.to_numeric(pd.Series([snapshot.get("season")]), errors="coerce").iloc[0]
        week = pd.to_numeric(pd.Series([snapshot.get("week")]), errors="coerce").iloc[0]
        normalized_name = _normalize_name(snapshot.get("player_name", ""))
        if pd.isna(season) or pd.isna(week) or not normalized_name:
            continue
        matches = frame[(frame["season"] == season) & (frame["week"] == week) & (frame["normalized_name"] == normalized_name)]
        if matches.empty:
            continue
        week_row = matches.iloc[0]
        position = str(snapshot.get("position") or week_row.get("position", ""))
        actual_points = calculate_fantasy_points(_actual_stat_payload(week_row), scoring, position)
        projected_points = _num(snapshot.get("projected_fantasy_points"))
        errors_by_position.setdefault(position, []).append(abs(actual_points - projected_points))
        graded_season = int(season)

    return _rows_from_errors_by_position("fantasy_nerds", graded_season, errors_by_position, "projection_snapshot_history.csv vs nflverse actuals")


def _actual_stat_payload(week_row: pd.Series) -> dict[str, Any]:
    return {f"projected_{field}": week_row.get(field, 0) for field in ACTUAL_STAT_FIELDS}


def _rows_from_errors_by_position(
    source: str, season: Any, errors_by_position: dict[str, list[float]], trace: str
) -> list[dict[str, Any]]:
    now = datetime.now(timezone.utc).isoformat()
    rows = []
    for position, errors in errors_by_position.items():
        sample_size = len(errors)
        if sample_size == 0:
            continue
        mae = round(sum(errors) / sample_size, 2)
        rows.append(
            {
                "source": source,
                "position": position,
                "season": season,
                "mean_absolute_error": mae,
                "sample_size": sample_size,
                "accuracy_confidence": _accuracy_confidence(sample_size, mae),
                "source_trace": trace,
                "checked_at": now,
            }
        )
    return rows


def _accuracy_confidence(sample_size: int, mae: float) -> str:
    # Weekly-fantasy-point-scale thresholds (a flat season-average PPG compared
    # against each individual week's actual, so natural week-to-week variance is
    # higher than a true weekly projection would show) -- same games-matched-count
    # gating precedent as _project_player's own confidence thresholds.
    if sample_size < 8:
        return "low"
    if mae <= 5.0:
        return "high"
    if mae <= 9.0:
        return "medium"
    return "low"


def _scoring_settings_from_leagues(leagues_df: pd.DataFrame) -> dict[str, float]:
    if leagues_df is None or leagues_df.empty or "scoring_settings" not in leagues_df:
        return {}
    raw = leagues_df.iloc[0].get("scoring_settings", "")
    try:
        parsed = json.loads(raw) if isinstance(raw, str) and raw else {}
        return {str(key): _num(value) for key, value in parsed.items()}
    except (TypeError, ValueError, json.JSONDecodeError):
        return {}


def _num(value: Any) -> float:
    try:
        if value in ("", None) or pd.isna(value):
            return 0.0
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def _accuracy_columns() -> list[str]:
    return ["source", "position", "season", "mean_absolute_error", "sample_size", "accuracy_confidence", "source_trace", "checked_at"]


def _snapshot_history_columns() -> list[str]:
    return ["season", "week", "source", "player_id", "player_name", "position", "projected_fantasy_points", "written_at"]
